services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - "54327:5432"
    environment:
      POSTGRES_PASSWORD: "@xZ0041105"
      POSTGRES_USER: sorasak
      POSTGRES_DB: sorasak
    volumes:
      - ./data/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: 69-s1-admin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  app:
    image: prawee/strapi
    container_name: 69-s1-app
    ports:
      - "9091:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: 69-s1-db
      DATABASE_PORT: 5432
      DATABASE_NAME: sorasak
      DATABASE_USERNAME: sorasak
      DATABASE_PASSWORD: "@xZ0041105"


